### ISSUE TITLE
"run", "run" are twice

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#13]
"run", "run" are twice, but "ran" (ran.jpg) in not in use.

**Comment by imiolek-ireneusz** [comment]
I think I was meant to remove the "ran" word because it would be difficult to tell the difference in the word matching games, but going through all translation word lists and looking for the right word was not in the agenda at that time.

This also proves the point (mentioned in issue #14 ) for the need of a file where words are matched to English ones rather than relying on an ordered list.
