### ISSUE TITLE
No pronounce for native langs

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#30]
No pronounce for "Українська", "Lakȟótiyapi" in dialog of languages.

**Comment by glixx** [comment]
Українська can be spoken by ru as Украинська by espeak.
Lakȟótiyapi can be spoken by Google translate and recorded; and play sound instead of espeak if it's enabled. It tried by Google translate to hear word and it can be spoken by en by espeak too.

**Comment by imiolek-ireneusz** [comment]
I think I misread the issue. So you are just referring to the language label in the lang selection activity. Espeak is disabled in those languages, because the rest of application does not support text to speak functionality either. I think I will leave the labels out as well so as not to give anyone hopes that they will have such functionality in the language. Would not really want to record the entire language.

**Comment by glixx** [comment]
Icon for espeak state should then to have the 3rd state : grey color and force disabled.
No way to know in GUI if no support in espeak or espeak did not installed.

**Comment by imiolek-ireneusz** [comment]
Will add another state. Haven't actually thought of that. When espeak is not installed the icon does not show up at all, but did not do anything to disable the icon when the TTS is not available for selected language.

**Comment by glixx** [comment]
It works good. 3rd state if no language support in espeak and no icon if espeak is not installed.
Important to add log in CHANGES.txt.

**Comment by imiolek-ireneusz** [comment]
Thanks. Also, I need to learn to keep on updating the CHANGES file - somehow currently I miss a lot of things in there.
