### ISSUE TITLE
espeak does not work

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#36]
Use Mageia 7 beta1: https://www.mageia.org/en/downloads/prerelease/
```
su -
urpmi eduactiv8
```
espeak works in console, but not in gui.

**Comment by imiolek-ireneusz** [comment]
I'm not sure what is going on with this one. I have installed the Mageia 7 beta release (using KDE desktop environment) - got all the latest updates.
The program installed without any issues with python3-pygame and it seems to talk to eSpeak. When changing languages it says what I have selected (after manually removing line 51 in /usr/share/eduactiv8/classes/lang.py, but when starting, for instance, a letter learning activity (017/005) after clicking on 8 letters (sometimes more) it stops as if the eSpeak subprocess stopped accepting new text to process. The quality of sound is very bad also, but that may be down to me running the Mageia via VirtualBox (since trying to play a random video also was not great).

**Comment by glixx** [comment]
Is it possible to see output of espeak?

**Comment by imiolek-ireneusz** [comment]
I tried to send the output to the stdout but so far no luck... I'll have another look at it when I get some time.

**Comment by imiolek-ireneusz** [comment]
Getting output form eSpeak, was actually easier than I thought... I just needed to stop hiding it ;)

When creating subprocess the stdout and stderr need to be removed, and also do not need to be closed later in the stop_server()

this is what the self.process initialization line in speaker.py file needs to look like to get all the output from eSpeak:

self.process = subprocess.Popen(cmd, shell=False, bufsize=0, stdin=subprocess.PIPE)

... and there's a lot of output there - probably that is what is clogging the whole process.
![virtualbox_mageia 7_30_01_2019_13_31_24](https://user-images.githubusercontent.com/6198330/51984638-bf501600-2493-11e9-8dba-f7f86c59b838.png)

There are hundreds of the 'underrun occurred' lines there. Could this be a potential issue in Mageia with the sound server?

**Comment by glixx** [comment]
Do you have patch?

**Comment by imiolek-ireneusz** [comment]
The latest change on the development should let you see all the output from eSpeak.
https://github.com/imiolek-ireneusz/eduActiv8/blob/development/classes/speaker.py

**Comment by glixx** [comment]
Package eduactiv8-4.19.01-0.6.git20190121.mga7.noarch.rpm works now.

**Comment by imiolek-ireneusz** [comment]
Not sure how, but I'm pleased you managed to get this issue resolved. I couldn't get this to work properly on Mageia. Thanks.
