### ISSUE TITLE
Ubuntu 22.04 deb file support

### ISSUE THREAD

**Issue by ale3andro** [imiolek-ireneusz/eduActiv8#43]
Hello,
is there a plan to create a deb file for Ubuntu 22.04 LTS?
Thank you

**Comment by imiolek-ireneusz** [comment]
Thanks for the report, I've just enabled the Ubuntu 22.04 support on the openSUSE Build Service and the project built successfully. The latest version should be available at: https://software.opensuse.org//download.html?project=home%3Aimiolek-i&package=eduactiv8

**Comment by ale3andro** [comment]
Thank you for the build.
Unfortunately I cannot install it on Ubuntu 22.04 LTS. Neither the deb file nor from the repo.
The error message is that is depends on python and python-pygame but both of them are not installable.
I have already installed python3 and python3-pygame. It seems to me that package python-pygame is not available in Ubuntu 22.04 repositories

**Comment by imiolek-ireneusz** [comment]
Thanks for getting back to me on that one. I'll get it fixed at some point but very likely not this week (reopening the issue). It seems this version has removed the support for Python 2 all together. I will have to find a way to configure the Build Service to use different versions of Python depending on the version of Ubuntu.

**Comment by imiolek-ireneusz** [comment]
It has proven a little bit tricky but I believe I have a working build that should run on Ubuntu 22.04 and other latest Linux distros that do support python3 and python3-pygame packages. It's a fresh build from the latest source I have and includes a little fix related to Pygame 2+ (the application would crash after the user logged in on a fresh install - due to the size of the window being larger than the screen, this has been changed to 800 x 600 on a new install, and then the user can resize the window as needed), more testing may be necessary to ensure everything works as expected.

The latest build is now added and enabled on the OpenSUSE Build Service:
https://software.opensuse.org/download.html?project=home%3Aimiolek-i&package=eduactiv8

**Comment by ale3andro** [comment]
I can confirm that I can install the application now in Ubuntu 22.04
Thank you very much

**Comment by imiolek-ireneusz** [comment]
That's fantastic. Thank you for testing and confirming it worked. Enjoy.
