### ISSUE TITLE
Use transifex for translations

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#8]
transifex.com is free for open source projects. It will help you to translate at least PO files.
And this issue https://github.com/imiolek-ireneusz/eduActiv8/issues/2 can be done faster if to have PO files and upload them into transifex. It's easy to convert back to your format.

**Comment by imiolek-ireneusz** [comment]
This looks great, I'm just trying to set the project up. I am struggling to upload the languages that have more than one plural form though, but I'll get there.

**Comment by glixx** [comment]
Transifex works with plural forms.

**Comment by imiolek-ireneusz** [comment]
I've got this sorted, the plurals were complaining because of a different number they were expecting. I had to remove them temporarily - will get them entered manually when I get a chance - some time next week. The project is now on Transifex.com. I will get the website sections about translations added next week as well. The word lists will be added as a separate resource.

https://www.transifex.com/eduactiv8/eduactiv8/

**Comment by glixx** [comment]
https://github.com/imiolek-ireneusz/eduActiv8/issues/4 I'm not sure POT file was uploaded are full. Default.py has more strings.

**Comment by glixx** [comment]
Just for information.
Transifex has database to keep all translators, who contributed PO files before.
Just add them into #Translators place of PO file and upload PO file into tx.
But sometimes it does not work, needs to contact tx support directly.

**Comment by imiolek-ireneusz** [comment]
Thanks for that... will check it out next time I update the translations; in the meantime, I added everybody between "X-Generator: ..." and the start of translations since Transifex replaced the headers completely removing all previous credits information I had in those files so I was hoping it will not touch this bit.

**Comment by glixx** [comment]
Add #Translators on your side and contact with tx support. I hope they will fix.

**Comment by glixx** [comment]
It should have format:

# Name_or_nick <email>, year

But import translators into tx is broken temporary, I contacted with tx support.

**Comment by imiolek-ireneusz** [comment]
Thanks for checking with tx.
I will look for the years and add them to the files on my end only until fixed by tx, that is when I get a chance.

**Comment by imiolek-ireneusz** [comment]
I have updated the website briefly. But will have to get in touch with the translators individually. But that will be on Monday. Unfortunately working full time (48 hours) and studying part-time does not leave a lot of time for anything else. 

I will also look into the other issues then.

**Comment by glixx** [comment]
I informed Mageia's translators, but they are busy. Mageia 7 is going to release soon and many strings needs to translate on tx too. Anyway they know about tx.

**Comment by imiolek-ireneusz** [comment]
Since the project is on the Transifex, all the conversion scripts are ready and all the people I could contact do know about the service I think I can now close this issue freely.

Thank you again for suggesting this great service - and also great of the Transifex to offer their services free to open source projects - so a massive thanks to the Transifex team.
